CREATE TABLE Flight(
ID INT AUTO_INCREMENT PRIMARY KEY,
flight_number VARCHAR(50) NOT NULL,
origin VARCHAR(100) NOT NULL,
destination VARCHAR(100) NOT NULL,
departure_time TIME NOT NULL,
arrival_time TIME NOT NULL,
price INT NOT NULL);